name: .NET Console Desktop Developing with dotnet-cli

on:
  push:
    branches-ignore:
      - master

env:
  Solution_Name_Portproxy: programs\portproxy.sln
  Firewall_Test_Project_Path: programs\tests\FireWallTest\FirewallTest.csproj
  Firewall_Test_Project_dir: programs\tests\FireWallTest
  Strategies_Test_Project_Path: programs\tests\StrategiesTest\StrategiesTest.csproj
  Strategies_Test_Project_dir: programs\tests\StrategiesTest
  Wsl_Test_Project_Path: programs\tests\WslTest\WslTest.csproj
  Wsl_Test_Project_dir: programs\tests\WslTest
  Ports_Test_Project_Path: programs\tests\PortsTest\PortsTest.csproj
  Ports_Test_Project_dir: programs\tests\PortsTest
  Solution_Test_Project_Path: programs\tests\SolutionTest\SolutionTest.csproj
  Solution_Test_Project_dir: programs\tests\SolutionTest
  Cache_Workplace_Key: ${{ github.workflow }}-workspace

jobs:
  checkout_dotnet:
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: store workspace cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-checkout-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

  restore_dotnet: 
    name: Restore packages
    runs-on: windows-2022
    needs: [ checkout_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-checkout-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-checkout-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
      
      - name: store cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      
      - name: Restore Packages
        run: nuget restore ${{ env.Solution_Name_Portproxy }} 

      - name: store workspace cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-restore-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
  
  build_dotnet: 
    name: Build Solution with dotnet
    runs-on: windows-2022
    needs: [ restore_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-restore-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-restore-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

      - name: restore cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: dotnet build
        run: dotnet build ${{ github.workspace }}\${{ env.Solution_Name_Portproxy }} -c ${{ matrix.configuration }} -f ${{ matrix.dotnet_version }} --no-restore

      - name: store workspace cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
   
  test_firewall_dotnet:
    name: Run firewall test dotnet
    runs-on: windows-2022
    needs: [ build_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

      - name: restore cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: dotnet test
        run: dotnet test ${{ github.workspace }}\${{ env.Firewall_Test_Project_Path }} -c ${{ matrix.configuration }} -f ${{ matrix.dotnet_version }} --collect "XPlat Code Coverage"
  
      - name: Upload artifact coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-firewall
          path: ${{ github.workspace }}\${{ env.Firewall_Test_Project_dir }}\TestResults\*\coverage.cobertura.xml
  
  test_strategies_dotnet:
    name: Run strategies test dotnet
    runs-on: windows-2022
    needs: [ build_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

      - name: restore cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: dotnet test
        run: dotnet test ${{ github.workspace }}\${{ env.Strategies_Test_Project_Path }} -c ${{ matrix.configuration }} -f ${{ matrix.dotnet_version }} --collect "XPlat Code Coverage"
  
      - name: Upload artifact coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-strategies
          path: ${{ github.workspace }}\${{ env.Strategies_Test_Project_dir }}\TestResults\*\coverage.cobertura.xml
  
  test_wsl_dotnet:
    name: Run Wsl test dotnet
    runs-on: windows-2022
    needs: [ build_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

      - name: restore cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: dotnet test
        run: dotnet test ${{ github.workspace }}\${{ env.Wsl_Test_Project_Path }} -c ${{ matrix.configuration }} -f ${{ matrix.dotnet_version }} --collect "XPlat Code Coverage"

      - name: Upload artifact coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-wsl
          path: ${{ github.workspace }}\${{ env.Wsl_Test_Project_dir }}\TestResults\*\coverage.cobertura.xml

  test_ports_dotnet:
    name: Run ports test dotnet
    runs-on: windows-2022
    needs: [ build_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

      - name: restore cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: dotnet test
        run: dotnet test ${{ github.workspace }}\${{ env.Ports_Test_Project_Path }} -c ${{ matrix.configuration }} -f ${{ matrix.dotnet_version }} --collect "XPlat Code Coverage"

      - name: Upload artifact coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-ports
          path: ${{ github.workspace }}\${{ env.Ports_Test_Project_dir }}\TestResults\*\coverage.cobertura.xml

  test_solution_dotnet:
    name: Run solution test dotnet
    runs-on: windows-2022
    needs: [ build_dotnet ]
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]
        dotnet_version: [ net6.0, net7.0 ]
    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: restore cache workspace 
        uses: actions/cache@v3
        with: 
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.Cache_Workplace_Key }}-build-${{ matrix.configuration}}-${{ matrix.platform }}-${{ matrix.dotnet_version }}-${{ github.run_id }}

      - name: restore cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.configuration }}-${{ matrix.dotnet_version }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: dotnet test
        run: dotnet test ${{ github.workspace }}\${{ env.Solution_Test_Project_Path }} -c ${{ matrix.configuration }} -f ${{ matrix.dotnet_version }} --collect "XPlat Code Coverage"
      
      - name: Upload artifact coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-solution
          path: ${{ github.workspace }}\${{ env.Solution_Test_Project_dir }}\TestResults\*\coverage.cobertura.xml